import { Room, Tenant, UtilityRates, RentInvoice } from '@/types/rentpulse';

export const DEFAULT_UTILITY_RATES: UtilityRates = {
  electricPerKwh: 2200,
  waterPerM3: 12000,
  wifiAndTrashFee: 60000,
  lateFeePerDay: 15000,
};

export const INITIAL_ROOMS: Room[] = [
  // Lantai 1
  {
    id: 'room-101',
    roomNumber: 'Kamar 101',
    floor: 1,
    type: 'AC_STANDARD',
    monthlyPrice: 1850000,
    status: 'TERISI',
    tenantId: 'ten-01',
    tenantName: 'Dimas Wicaksono',
    tenantPhone: '081299887766',
    facilities: ['AC 1/2 PK', 'Kamar Mandi Dalam', 'Kasur Springbed', 'Lemari Pakaian', 'Meja Kerja'],
    lastElectricKwh: 420,
    lastWaterM3: 18,
  },
  {
    id: 'room-102',
    roomNumber: 'Kamar 102',
    floor: 1,
    type: 'AC_DELUXE',
    monthlyPrice: 2250000,
    status: 'MENUNGGAK',
    tenantId: 'ten-02',
    tenantName: 'Fajar Nugraha',
    tenantPhone: '081377665544',
    facilities: ['AC 1 PK', 'Water Heater', 'Smart TV 32"', 'Kamar Mandi Dalam', 'Balkon'],
    lastElectricKwh: 580,
    lastWaterM3: 24,
    notes: 'Jatuh tempo tanggal 20 September. Terlambat 4 hari.',
  },
  {
    id: 'room-103',
    roomNumber: 'Kamar 103',
    floor: 1,
    type: 'NON_AC',
    monthlyPrice: 1100000,
    status: 'KOSONG',
    facilities: ['Kipas Angin Dinding', 'Kamar Mandi Luar', 'Kasur Busa', 'Lemari'],
    lastElectricKwh: 110,
    lastWaterM3: 6,
  },
  {
    id: 'room-104',
    roomNumber: 'Kamar 104',
    floor: 1,
    type: 'AC_STANDARD',
    monthlyPrice: 1850000,
    status: 'PERBAIKAN',
    facilities: ['AC 1/2 PK', 'Kamar Mandi Dalam', 'Kasur Springbed'],
    lastElectricKwh: 310,
    lastWaterM3: 12,
    notes: 'Sedang pengecatan ulang dinding dan servis AC berkala.',
  },

  // Lantai 2
  {
    id: 'room-201',
    roomNumber: 'Kamar 201',
    floor: 2,
    type: 'AC_STANDARD',
    monthlyPrice: 1900000,
    status: 'TERISI',
    tenantId: 'ten-03',
    tenantName: 'Siti Sarah Rahmawati',
    tenantPhone: '081512349876',
    facilities: ['AC 1/2 PK', 'Kamar Mandi Dalam', 'Jendela Hadap Taman', 'Meja Belajar'],
    lastElectricKwh: 345,
    lastWaterM3: 15,
  },
  {
    id: 'room-202',
    roomNumber: 'Kamar 202',
    floor: 2,
    type: 'AC_DELUXE',
    monthlyPrice: 2300000,
    status: 'KOSONG',
    facilities: ['AC 1 PK', 'Kulkas Mini', 'Water Heater', 'Kamar Mandi Dalam'],
    lastElectricKwh: 12,
    lastWaterM3: 2,
  },
  {
    id: 'room-203',
    roomNumber: 'Kamar 203',
    floor: 2,
    type: 'AC_STANDARD',
    monthlyPrice: 1900000,
    status: 'TERISI',
    tenantId: 'ten-04',
    tenantName: 'Kevin Anggara',
    tenantPhone: '081765432109',
    facilities: ['AC 1/2 PK', 'Kamar Mandi Dalam', 'High Speed LAN'],
    lastElectricKwh: 490,
    lastWaterM3: 19,
  },
  {
    id: 'room-204',
    roomNumber: 'Kamar 204',
    floor: 2,
    type: 'NON_AC',
    monthlyPrice: 1150000,
    status: 'KOSONG',
    facilities: ['Exhaust Fan', 'Kasur Single', 'Lemari', 'Kamar Mandi Luar'],
    lastElectricKwh: 40,
    lastWaterM3: 4,
  },

  // Ruko Depan
  {
    id: 'room-ruko-1',
    roomNumber: 'Ruko A-1 Depan',
    floor: 1,
    type: 'RUKO_DEPAN',
    monthlyPrice: 4500000,
    status: 'TERISI',
    tenantId: 'ten-05',
    tenantName: 'Kopi Kenangan Senja (Barista)',
    tenantPhone: '081988112233',
    facilities: ['Rolling Door Otomatis', 'Listrik 4400 Watt', 'Air PDAM Mandiri', 'Toilet Dalam'],
    lastElectricKwh: 1240,
    lastWaterM3: 54,
  },
];

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'ten-01',
    fullName: 'Dimas Wicaksono',
    nik: '3201123456780001',
    phone: '081299887766',
    roomId: 'room-101',
    roomNumber: 'Kamar 101',
    jobOrCampus: 'Software Engineer di Tech Co.',
    emergencyContact: {
      name: 'Bambang Wicaksono',
      relationship: 'Orang Tua (Ayah)',
      phone: '081122334455',
    },
    startDate: '2026-02-01',
    depositPaid: 1850000,
  },
  {
    id: 'ten-02',
    fullName: 'Fajar Nugraha',
    nik: '3201123456780002',
    phone: '081377665544',
    roomId: 'room-102',
    roomNumber: 'Kamar 102',
    jobOrCampus: 'Digital Marketer',
    emergencyContact: {
      name: 'Rina Nugraha',
      relationship: 'Kakak Kandung',
      phone: '081233445566',
    },
    startDate: '2026-05-15',
    depositPaid: 2250000,
  },
];
